### PR TITLE
Update to Android Studio 3.0

### PR DESCRIPTION
**Pull request by alexfu**
Updates build tools and gradle to be compatible with Android Studio 3.0. Also updates dependencies.

### CODE REVIEW

**Comment by alexfu** [comment]
The SDK currently targets API 19, @schukin do you have any interest in updating it to 23?

**Comment by schukin** [comment]
Hmmm... Not sure we want to drop Lollipop support just yet (over [25% users on Lollipop](https://developer.android.com/about/dashboards/index.html)). Perhaps KitKat though. Let's brew on this one a bit.

**Comment by alexfu** [comment]
@schukin Oh, I think you're thinking of `minSDK`. I was talking about `targetSDK`.

**Comment by schukin** [comment]
@alexfu ah, my bad. Sure, we can bump it up to 23... although any reason we shouldn't just bump it up to the latest?

**Comment by alexfu** [comment]
@schukin I don't see a reason to not bump to 23.

**Pull request merged**
